description = "A CDE/Solaris-inspired retro theme for Hugo."
features    = ["rss", "webmentions", "indieweb", "giscus"]
homepage    = "https://github.com/RdrSeraphim/srplife_theme"
license     = "MIT"
licenselink = "https://github.com/RdrSeraphim/srplife_theme/blob/main/LICENSE"
min_version = "0.163.0"
name        = "srplife"
tags        = ["retro", "cde", "solaris", "blog", "personal"]

[author]
homepage = "https://srp.life"
name     = "Seraphim Pardee"
